version: '3'
services:
  db:
    image: mydb
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dcard
    ports:
      - '3306:3306'
  backend:
    image: api
    depends_on:
      - db
    ports:
      - '8080:8080'
    
